id: A402D3202
title: 'The Summoning Hook of Wish-Fulfilment: An Appeal for Prosperity'
type: translation
pechas:
- I2419A3A1
- I5DAF041B
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:56:15.742221
  last_modified_at: 2023-01-04 12:56:15.742244
  collections:
  - Könchok Tenpe Drönme Series
  - Works of Tibetan Masters
alignment_to_base:
  I2419A3A1/1FA5: FAE1
  I5DAF041B/ED48: FAE1
